name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 16.171.20.84 >> ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        ssh ubuntu@16.171.20.84 << 'EOF'
          cd ~/clickrwanda-server || git clone https://github.com/Diibro/clickrwanda-server.git ~/clickrwanda-server
          cd ~/clickrwanda-server
          git pull
           # Create .env file from secrets.PROD_ENV_FILE
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          npm install
          pm2 restart all || pm2 start index.js --name clickrwanda-server
        EOF
        
